% Thu 22 Sep 17:31:22 CEST 2016
% Karl Kastner, Berlin
%
% create an slg-object from a selected indices
%
% This programme is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This programme is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this programme. If not, see <https://www.gnu.org/licenses/>.
%
function slg=select(slg,fdx)
	field_C = {...
	'quality', ...
	'time', ...
	'UpperLimit', ...
	'LowerLimit', ...
	'DepthValid', ...
	'Depth', ...
	'WaterTempValid', ...
	'WaterTemp', ...
	'Temp2Valid', ...
	'Temp2', ...
	'Temp3Valid', ...
	'Temp3', ...
	'WaterSpeedValid', ...
	'WaterSpeed', ...
	'PositionValid', ...
	'PositionX', ...
	'PositionY', ...
	'SurfaceValid', ...
	'SurfaceDepth', ...
	'TopOfBottomValid', ...
	'TopOfBottomDepth', ...
	'ColumnIs50kHz', ...
	'TimeValid', ...
	'TimeOffset', ...
	'SpeedTrackValid', ...
	'Speed', ...
	'Track', ...
	'AltitudeValid', ...
	'Altitude', ...
	};
	for idx=1:length(field_C)
		slg.(field_C{idx}) = slg.(field_C{idx})(fdx);
	end 
	if (~isempty(slg.ECHO))
		slg.ECHO=slg.ECHO(:,fdx);
	end
end % select

